ui: mocha-bdd
concurrency: 2
tunnel:
  type: ngrok
browserify:
  - transform: babelify
  - transform: envify
browsers:
  - name: chrome
    version: 60..latest
  - name: firefox
    version: 55..latest
  - name: safari
    version: [9, 10, latest]
  - name: ie
    version: [10, 11]
  - name: microsoftedge
    version: 14..latest
  - name: iphone
    version: [9.0, 10.0, latest]
  - name: android
    version: 4.4..latest
