ui: mocha-bdd
concurrency: 2
tunnel:
  type: ngrok
browserify:
  - transform: babelify
  - transform: envify
browsers:
  - name: chrome
    version: 50..latest
  - name: firefox
    version: 46..latest
  - name: safari
    version: [6, 7, 8, 9..latest]
  - name: ie
    version: 10..11
  - name: microsoftedge
    version: 13..latest
  - name: iphone
    version: [7.0, 8.4, 9.0, 10.0]
  - name: android
    version: 4.4..latest
