ui: mocha-bdd
concurrency: 1
tunnel:
  type: ngrok
browserify:
  - transform: bubleify
  - transform: envify
browsers:
  - name: chrome
    version: [75, latest]
  - name: firefox
    version: [60, latest]
  - name: safari
    version: [10, latest]
  - name: ie
    version: [11]
  - name: MicrosoftEdge
    version: [17, latest]
  - name: iphone
    version: [11, latest]
  - name: android
    version: [5, 6]
