ui: mocha-bdd
concurrency: 2
tunnel:
  type: ngrok
browserify:
  - transform: bubleify
  - transform: envify
browsers:
  - name: chrome
    version: 62..latest
  - name: firefox
    version: 56..latest
  - name: safari
    version: [9, 10, latest]
  - name: ie
    version: [10, 11]
  - name: MicrosoftEdge
    version: 14..latest
  - name: iphone
    version: [9.0, 10.0, latest]
  - name: android
    version: [4.4, 5.0, 6.0]
