ui: mocha-bdd
tunnel:
  type: localtunnel
  https: true
browserify:
  - transform: babelify
  - transform: envify
browsers:
  - name: chrome
    version: 45..latest
  - name: firefox
    version: 40..latest
  - name: safari
    version: [6, 7, 8, 9..latest]
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: 13..latest
  - name: iphone
    version: [7.0, 8.2, 9.0]
  - name: android
    version: 4.4..latest
